# Generated by Django 4.2.7 on 2023-11-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30)),
                ('image', models.ImageField(default='def.png', upload_to='prof_pic/')),
                ('address', models.TextField(max_length=100)),
                ('phone_number', models.TextField(max_length=15)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], max_length=8)),
                ('religion', models.CharField(choices=[('ISLAM', 'ISLAM'), ('HINDU', 'HINDU'), ('BUDDHO', 'BUDDHO'), ('KRISTIAN', 'KRISTIAN')], max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.TextField(max_length=10)),
            ],
        ),
    ]
